### ISSUE TITLE
Can run on the simulator ,but can not run on the iPhone device

### ISSUE THREAD

**Issue by realcarlos** [kishikawakatsumi/JapaneseKeyboardKit#1]
I use iPhone5 (iOS 8.0.2) ,Xcode 6.0.1

**Comment by kishikawakatsumi** [comment]
Thank you for reporting. It seems 32bit/64bit issue. I'll fix it as soon as possible.

**Comment by kishikawakatsumi** [comment]
Fixed
- https://github.com/kishikawakatsumi/Mozc-for-iOS/pull/2
- https://github.com/kishikawakatsumi/JapaneseKeyboardKit/commit/647f823edbc4191d5c53eed147c91a09d72f7c91
